<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<!DOCTYPE html>
<html>
<head>
  <title>2FA Verification</title>
</head>
<body>
<h1>Two-Factor Authentication</h1>
<p>Enter the OTP generated by your authenticator app:</p>
<form action="verify" method="post">
  <label for="otp">TOTP:</label>
  <input type="text" name="otp" id="otp" required>
  <br/>
  <button type="submit">Verify</button>
</form>
</body>
</html>