<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<!DOCTYPE html>
<html>
<head>
  <title>2FA Verification</title>
</head>
<body>
<h1>Two-Factor Authentication</h1>
<p>Enter the OTP generated by your authenticator app:</p>
<form action="${pageContext.request.contextPath}/verify" method="post">
  <label for="otp">Enter OTP:</label>
  <input type="text" id="otp" name="otp" required>
  <button type="submit">Verify OTP</button>
</form>
<p style="color:red;"><%= request.getParameter("error") %></p>
</body>
</html>